export const environment = {
  production: true,
  apiBaseUrl: 'https://groupchatbackend-41bl.onrender.com/api/v1',
  applicationName: 'GroupChat',
  applicationVersion: '1.0.0',
  indexedDBName: 'GroupChatDB',
  indexedDBVersion: 1,
  enableResponseCacheProcessing: true,
  apiResponseCacheTimeoutInMinutes: 5,
  LoggingInfo: {
    LogLocation: 'Console',
    ExceptionLocation: 'Console',
    logToConsole: false,
    logToFile: false,
    logToApi: true,
    logToElasticCluster: false,
    exceptionToConsole: false,
    exceptionToFile: false,
    exceptionToApi: true,
    exceptionToElasticCluster: false,
    cacheLogs: false,
  },
  encryptionKey: '12345678901234567890123456789012',
};
